// Generated by npm run docs:generate-rpc-usage
// Source commit: 207c85fc41d2bc1cab36797deebc5af6ffea7ce0
// Do not edit manually.

import type { PublicRpcName, RpcArgs, RpcReturns, RpcRow } from "./rpc.types";

export const CONSUMED_RPC_NAMES = [
  "accept_ticket_transfer",
  "admin_archive_ticket_lot",
  "admin_clear_person_profile",
  "admin_delete_person_profile",
  "admin_get_person_details",
  "admin_get_profile_claim_disputes_with_identity",
  "admin_get_ticket_lots",
  "admin_import_people",
  "admin_update_person_and_profile",
  "admin_upsert_ticket_lot",
  "apply_mercado_pago_payment",
  "calculate_refund_quote",
  "cancel_guest_approval_request",
  "cancel_ticket_transfer",
  "claim_notification_jobs",
  "complete_notification_job",
  "complete_profile_registration_v2",
  "complete_profile_registration_v3",
  "create_checkout_order",
  "create_guest_approval_request",
  "export_checkin_report",
  "fn_increment_sold",
  "get_admin_orders",
  "get_admin_refund_requests",
  "get_checkin_activity",
  "get_checkin_dashboard",
  "get_checkin_operation_metrics",
  "get_checkout_status_by_token",
  "get_current_ticket_catalog",
  "get_event_reports",
  "get_my_commerce_orders",
  "get_my_guest_approval_requests",
  "get_my_ticket_transfers",
  "get_public_ticket_catalog",
  "has_structured_faq_items",
  "move_faq_category_items",
  "perform_ticket_checkin",
  "reject_ticket_transfer",
  "reorder_faq_categories",
  "reorder_faq_items",
  "request_order_refund",
  "request_ticket_resend",
  "request_ticket_transfer",
  "respond_guest_approval_request",
  "restore_refunded_order_inventory",
  "retry_order_payment",
  "review_refund_request",
  "search_external_guest_sponsors",
  "set_participant_vouchers_delivered",
  "update_my_public_profile"
] as const satisfies readonly PublicRpcName[];

export type ConsumedRpcName = (typeof CONSUMED_RPC_NAMES)[number];

export type AcceptTicketTransferArgs = RpcArgs<"accept_ticket_transfer">;
export type AcceptTicketTransferReturns = RpcReturns<"accept_ticket_transfer">;
export type AcceptTicketTransferRow = RpcRow<"accept_ticket_transfer">;

export type AdminArchiveTicketLotArgs = RpcArgs<"admin_archive_ticket_lot">;
export type AdminArchiveTicketLotReturns = RpcReturns<"admin_archive_ticket_lot">;
export type AdminArchiveTicketLotRow = RpcRow<"admin_archive_ticket_lot">;

export type AdminClearPersonProfileArgs = RpcArgs<"admin_clear_person_profile">;
export type AdminClearPersonProfileReturns = RpcReturns<"admin_clear_person_profile">;
export type AdminClearPersonProfileRow = RpcRow<"admin_clear_person_profile">;

export type AdminDeletePersonProfileArgs = RpcArgs<"admin_delete_person_profile">;
export type AdminDeletePersonProfileReturns = RpcReturns<"admin_delete_person_profile">;
export type AdminDeletePersonProfileRow = RpcRow<"admin_delete_person_profile">;

export type AdminGetPersonDetailsArgs = RpcArgs<"admin_get_person_details">;
export type AdminGetPersonDetailsReturns = RpcReturns<"admin_get_person_details">;
export type AdminGetPersonDetailsRow = RpcRow<"admin_get_person_details">;

export type AdminGetProfileClaimDisputesWithIdentityArgs = RpcArgs<"admin_get_profile_claim_disputes_with_identity">;
export type AdminGetProfileClaimDisputesWithIdentityReturns = RpcReturns<"admin_get_profile_claim_disputes_with_identity">;
export type AdminGetProfileClaimDisputesWithIdentityRow = RpcRow<"admin_get_profile_claim_disputes_with_identity">;

export type AdminGetTicketLotsArgs = RpcArgs<"admin_get_ticket_lots">;
export type AdminGetTicketLotsReturns = RpcReturns<"admin_get_ticket_lots">;
export type AdminGetTicketLotsRow = RpcRow<"admin_get_ticket_lots">;

export type AdminImportPeopleArgs = RpcArgs<"admin_import_people">;
export type AdminImportPeopleReturns = RpcReturns<"admin_import_people">;
export type AdminImportPeopleRow = RpcRow<"admin_import_people">;

export type AdminUpdatePersonAndProfileArgs = RpcArgs<"admin_update_person_and_profile">;
export type AdminUpdatePersonAndProfileReturns = RpcReturns<"admin_update_person_and_profile">;
export type AdminUpdatePersonAndProfileRow = RpcRow<"admin_update_person_and_profile">;

export type AdminUpsertTicketLotArgs = RpcArgs<"admin_upsert_ticket_lot">;
export type AdminUpsertTicketLotReturns = RpcReturns<"admin_upsert_ticket_lot">;
export type AdminUpsertTicketLotRow = RpcRow<"admin_upsert_ticket_lot">;

export type ApplyMercadoPagoPaymentArgs = RpcArgs<"apply_mercado_pago_payment">;
export type ApplyMercadoPagoPaymentReturns = RpcReturns<"apply_mercado_pago_payment">;
export type ApplyMercadoPagoPaymentRow = RpcRow<"apply_mercado_pago_payment">;

export type CalculateRefundQuoteArgs = RpcArgs<"calculate_refund_quote">;
export type CalculateRefundQuoteReturns = RpcReturns<"calculate_refund_quote">;
export type CalculateRefundQuoteRow = RpcRow<"calculate_refund_quote">;

export type CancelGuestApprovalRequestArgs = RpcArgs<"cancel_guest_approval_request">;
export type CancelGuestApprovalRequestReturns = RpcReturns<"cancel_guest_approval_request">;
export type CancelGuestApprovalRequestRow = RpcRow<"cancel_guest_approval_request">;

export type CancelTicketTransferArgs = RpcArgs<"cancel_ticket_transfer">;
export type CancelTicketTransferReturns = RpcReturns<"cancel_ticket_transfer">;
export type CancelTicketTransferRow = RpcRow<"cancel_ticket_transfer">;

export type ClaimNotificationJobsArgs = RpcArgs<"claim_notification_jobs">;
export type ClaimNotificationJobsReturns = RpcReturns<"claim_notification_jobs">;
export type ClaimNotificationJobsRow = RpcRow<"claim_notification_jobs">;

export type CompleteNotificationJobArgs = RpcArgs<"complete_notification_job">;
export type CompleteNotificationJobReturns = RpcReturns<"complete_notification_job">;
export type CompleteNotificationJobRow = RpcRow<"complete_notification_job">;

export type CompleteProfileRegistrationV2Args = RpcArgs<"complete_profile_registration_v2">;
export type CompleteProfileRegistrationV2Returns = RpcReturns<"complete_profile_registration_v2">;
export type CompleteProfileRegistrationV2Row = RpcRow<"complete_profile_registration_v2">;

export type CompleteProfileRegistrationV3Args = RpcArgs<"complete_profile_registration_v3">;
export type CompleteProfileRegistrationV3Returns = RpcReturns<"complete_profile_registration_v3">;
export type CompleteProfileRegistrationV3Row = RpcRow<"complete_profile_registration_v3">;

export type CreateCheckoutOrderArgs = RpcArgs<"create_checkout_order">;
export type CreateCheckoutOrderReturns = RpcReturns<"create_checkout_order">;
export type CreateCheckoutOrderRow = RpcRow<"create_checkout_order">;

export type CreateGuestApprovalRequestArgs = RpcArgs<"create_guest_approval_request">;
export type CreateGuestApprovalRequestReturns = RpcReturns<"create_guest_approval_request">;
export type CreateGuestApprovalRequestRow = RpcRow<"create_guest_approval_request">;

export type ExportCheckinReportArgs = RpcArgs<"export_checkin_report">;
export type ExportCheckinReportReturns = RpcReturns<"export_checkin_report">;
export type ExportCheckinReportRow = RpcRow<"export_checkin_report">;

export type FnIncrementSoldArgs = RpcArgs<"fn_increment_sold">;
export type FnIncrementSoldReturns = RpcReturns<"fn_increment_sold">;
export type FnIncrementSoldRow = RpcRow<"fn_increment_sold">;

export type GetAdminOrdersArgs = RpcArgs<"get_admin_orders">;
export type GetAdminOrdersReturns = RpcReturns<"get_admin_orders">;
export type GetAdminOrdersRow = RpcRow<"get_admin_orders">;

export type GetAdminRefundRequestsArgs = RpcArgs<"get_admin_refund_requests">;
export type GetAdminRefundRequestsReturns = RpcReturns<"get_admin_refund_requests">;
export type GetAdminRefundRequestsRow = RpcRow<"get_admin_refund_requests">;

export type GetCheckinActivityArgs = RpcArgs<"get_checkin_activity">;
export type GetCheckinActivityReturns = RpcReturns<"get_checkin_activity">;
export type GetCheckinActivityRow = RpcRow<"get_checkin_activity">;

export type GetCheckinDashboardArgs = RpcArgs<"get_checkin_dashboard">;
export type GetCheckinDashboardReturns = RpcReturns<"get_checkin_dashboard">;
export type GetCheckinDashboardRow = RpcRow<"get_checkin_dashboard">;

export type GetCheckinOperationMetricsArgs = RpcArgs<"get_checkin_operation_metrics">;
export type GetCheckinOperationMetricsReturns = RpcReturns<"get_checkin_operation_metrics">;
export type GetCheckinOperationMetricsRow = RpcRow<"get_checkin_operation_metrics">;

export type GetCheckoutStatusByTokenArgs = RpcArgs<"get_checkout_status_by_token">;
export type GetCheckoutStatusByTokenReturns = RpcReturns<"get_checkout_status_by_token">;
export type GetCheckoutStatusByTokenRow = RpcRow<"get_checkout_status_by_token">;

export type GetCurrentTicketCatalogArgs = RpcArgs<"get_current_ticket_catalog">;
export type GetCurrentTicketCatalogReturns = RpcReturns<"get_current_ticket_catalog">;
export type GetCurrentTicketCatalogRow = RpcRow<"get_current_ticket_catalog">;

export type GetEventReportsArgs = RpcArgs<"get_event_reports">;
export type GetEventReportsReturns = RpcReturns<"get_event_reports">;
export type GetEventReportsRow = RpcRow<"get_event_reports">;

export type GetMyCommerceOrdersArgs = RpcArgs<"get_my_commerce_orders">;
export type GetMyCommerceOrdersReturns = RpcReturns<"get_my_commerce_orders">;
export type GetMyCommerceOrdersRow = RpcRow<"get_my_commerce_orders">;

export type GetMyGuestApprovalRequestsArgs = RpcArgs<"get_my_guest_approval_requests">;
export type GetMyGuestApprovalRequestsReturns = RpcReturns<"get_my_guest_approval_requests">;
export type GetMyGuestApprovalRequestsRow = RpcRow<"get_my_guest_approval_requests">;

export type GetMyTicketTransfersArgs = RpcArgs<"get_my_ticket_transfers">;
export type GetMyTicketTransfersReturns = RpcReturns<"get_my_ticket_transfers">;
export type GetMyTicketTransfersRow = RpcRow<"get_my_ticket_transfers">;

export type GetPublicTicketCatalogArgs = RpcArgs<"get_public_ticket_catalog">;
export type GetPublicTicketCatalogReturns = RpcReturns<"get_public_ticket_catalog">;
export type GetPublicTicketCatalogRow = RpcRow<"get_public_ticket_catalog">;

export type HasStructuredFaqItemsArgs = RpcArgs<"has_structured_faq_items">;
export type HasStructuredFaqItemsReturns = RpcReturns<"has_structured_faq_items">;
export type HasStructuredFaqItemsRow = RpcRow<"has_structured_faq_items">;

export type MoveFaqCategoryItemsArgs = RpcArgs<"move_faq_category_items">;
export type MoveFaqCategoryItemsReturns = RpcReturns<"move_faq_category_items">;
export type MoveFaqCategoryItemsRow = RpcRow<"move_faq_category_items">;

export type PerformTicketCheckinArgs = RpcArgs<"perform_ticket_checkin">;
export type PerformTicketCheckinReturns = RpcReturns<"perform_ticket_checkin">;
export type PerformTicketCheckinRow = RpcRow<"perform_ticket_checkin">;

export type RejectTicketTransferArgs = RpcArgs<"reject_ticket_transfer">;
export type RejectTicketTransferReturns = RpcReturns<"reject_ticket_transfer">;
export type RejectTicketTransferRow = RpcRow<"reject_ticket_transfer">;

export type ReorderFaqCategoriesArgs = RpcArgs<"reorder_faq_categories">;
export type ReorderFaqCategoriesReturns = RpcReturns<"reorder_faq_categories">;
export type ReorderFaqCategoriesRow = RpcRow<"reorder_faq_categories">;

export type ReorderFaqItemsArgs = RpcArgs<"reorder_faq_items">;
export type ReorderFaqItemsReturns = RpcReturns<"reorder_faq_items">;
export type ReorderFaqItemsRow = RpcRow<"reorder_faq_items">;

export type RequestOrderRefundArgs = RpcArgs<"request_order_refund">;
export type RequestOrderRefundReturns = RpcReturns<"request_order_refund">;
export type RequestOrderRefundRow = RpcRow<"request_order_refund">;

export type RequestTicketResendArgs = RpcArgs<"request_ticket_resend">;
export type RequestTicketResendReturns = RpcReturns<"request_ticket_resend">;
export type RequestTicketResendRow = RpcRow<"request_ticket_resend">;

export type RequestTicketTransferArgs = RpcArgs<"request_ticket_transfer">;
export type RequestTicketTransferReturns = RpcReturns<"request_ticket_transfer">;
export type RequestTicketTransferRow = RpcRow<"request_ticket_transfer">;

export type RespondGuestApprovalRequestArgs = RpcArgs<"respond_guest_approval_request">;
export type RespondGuestApprovalRequestReturns = RpcReturns<"respond_guest_approval_request">;
export type RespondGuestApprovalRequestRow = RpcRow<"respond_guest_approval_request">;

export type RestoreRefundedOrderInventoryArgs = RpcArgs<"restore_refunded_order_inventory">;
export type RestoreRefundedOrderInventoryReturns = RpcReturns<"restore_refunded_order_inventory">;
export type RestoreRefundedOrderInventoryRow = RpcRow<"restore_refunded_order_inventory">;

export type RetryOrderPaymentArgs = RpcArgs<"retry_order_payment">;
export type RetryOrderPaymentReturns = RpcReturns<"retry_order_payment">;
export type RetryOrderPaymentRow = RpcRow<"retry_order_payment">;

export type ReviewRefundRequestArgs = RpcArgs<"review_refund_request">;
export type ReviewRefundRequestReturns = RpcReturns<"review_refund_request">;
export type ReviewRefundRequestRow = RpcRow<"review_refund_request">;

export type SearchExternalGuestSponsorsArgs = RpcArgs<"search_external_guest_sponsors">;
export type SearchExternalGuestSponsorsReturns = RpcReturns<"search_external_guest_sponsors">;
export type SearchExternalGuestSponsorsRow = RpcRow<"search_external_guest_sponsors">;

export type SetParticipantVouchersDeliveredArgs = RpcArgs<"set_participant_vouchers_delivered">;
export type SetParticipantVouchersDeliveredReturns = RpcReturns<"set_participant_vouchers_delivered">;
export type SetParticipantVouchersDeliveredRow = RpcRow<"set_participant_vouchers_delivered">;

export type UpdateMyPublicProfileArgs = RpcArgs<"update_my_public_profile">;
export type UpdateMyPublicProfileReturns = RpcReturns<"update_my_public_profile">;
export type UpdateMyPublicProfileRow = RpcRow<"update_my_public_profile">;
