// Generated by npm run docs:generate-rpc-usage
// Bootstrap placeholder; the Phase 1 workflow replaces this file from the runtime inventory.
// Do not edit manually.

import type { PublicRpcName } from "./rpc.types";

export const CONSUMED_RPC_NAMES = [] as const satisfies readonly PublicRpcName[];
export type ConsumedRpcName = (typeof CONSUMED_RPC_NAMES)[number];
