import type { Page } from "@playwright/test";

export const restoredSections = [
  { key: "hero", label: "Hero", is_visible: true, sort_order: 10 },
  { key: "about", label: "Sobre", is_visible: true, sort_order: 20 },
  { key: "info", label: "Informacoes do evento", is_visible: true, sort_order: 30 },
  { key: "tickets", label: "Ingressos", is_visible: true, sort_order: 40 },
  { key: "confirmed", label: "Confirmados", is_visible: true, sort_order: 50 },
  { key: "photos", label: "Fotos", is_visible: true, sort_order: 60 },
  { key: "timeline", label: "Linha do tempo", is_visible: true, sort_order: 70 },
  { key: "faq", label: "FAQ", is_visible: true, sort_order: 80 },
];

export const restoredAboutCopy = {
  stats_total_label: "TOTAL DE ALUNOS CONCLUINTES",
  stats_confirmed_label: "Confirmados",
  stats_memories_label: "Memorias",
  timeline_label: "Linha do tempo",
  timeline_title_template: "{total} marcos da turma",
  timeline_description: "Momentos da turma.",
  memories_label: "Memorias",
  memories_title_template: "{total} memorias publicadas",
  memories_empty_title: "Memorias em construcao",
  memories_description: "Relatos da turma.",
  polls_label: "Enquetes",
  polls_title: "Perguntas da turma",
  polls_description: "Votacoes da turma.",
  charts_label: "Graficos",
  charts_title: "Raio-X em numeros",
  charts_description: "Indicadores da turma.",
  profile_label: "Perfil",
  profile_title_template: "{total} perfis cadastrados",
  profile_description: "Perfis cadastrados.",
  map_label: "Mapa da turma",
  map_title: "Onde cada um esta",
  map_description: "Distribuicao geografica.",
  view_all_label: "Ver tudo",
};

const alumniCopy = {
  eyebrow: "Ex-alunos",
  title: "A turma em movimento",
  description: "Indicadores atualizados da turma.",
  sample_label: "Amostra da turma",
  sample_title_template: "{total} ex-alunos cadastrados",
  presence_label: "Presenca",
  presence_title: "Reencontro em formacao",
  confirmed_label: "Confirmados",
  intending_label: "Pretendem ir",
  progress_label: "Confirmados sobre a base cadastrada",
  classes_label: "Turmas",
  classes_title: "Distribuicao por sala",
  confirmed_grid_label: "Confirmados",
  confirmed_grid_title: "Quem confirmou presenca",
  footer_note: "Dados atualizados da base da turma.",
  view_all_label: "Ver todos",
  class_tab_label_template: "Turma {group} ({count})",
  class_pagination_template: "Mostrando {start}-{end} de {total}",
  class_empty_label: "Turma sem registros",
  confirmed_empty_label: "Nenhuma confirmacao publicada.",
};

export const peopleFixture = Array.from({ length: 8 }, (_, index) => ({
  id: `00000000-0000-0000-0002-${String(index + 1).padStart(12, "0")}`,
  full_name: `Pessoa Confirmada ${index + 1}`,
  display_name: `Pessoa ${index + 1}`,
  class_year: 2006,
  class_group: ["A", "Turma B", "Sala C", "D"][index % 4],
  gender: index % 2 ? "male" : "female",
  nickname_at_school: null,
  profile_status: index < 6 ? "confirmed" : "claimed",
  claimed_by_user_id: null,
  claimed_at: null,
  is_visible: true,
  private_notes: null,
  avatar_url: null,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
}));

export const homeContentFixture: Record<string, unknown> = {
  event_id: "00000000-0000-0000-0000-000000000001",
  header_logo_url: null,
  header_logo_alt: "Marca do reencontro",
  header_fallback_badge_main: "HC",
  header_fallback_badge_year: "20",
  header_fallback_title: "Turma 2006",
  header_fallback_subtitle: "20 anos",
  header_cta_label: "Comprar ingresso",
  header_cta_visible: true,
  header_auth_visible: true,
  nav_home_label: "Home",
  nav_event_label: "Evento",
  nav_ex_alumni_label: "Ex-alunos",
  nav_who_going_label: "Quem vai",
  nav_the_class_label: "A turma",
  nav_photos_label: "Fotos",
  nav_memories_label: "Memorias",
  nav_polls_label: "Curiosidades",
  nav_where_now_label: "Onde estao",
  nav_archive_label: "Pos-festa",
  nav_home_visible: true,
  nav_event_visible: true,
  nav_ex_alumni_visible: true,
  nav_who_going_visible: true,
  nav_the_class_visible: true,
  nav_photos_visible: true,
  nav_memories_visible: true,
  nav_polls_visible: true,
  nav_where_now_visible: true,
  nav_archive_visible: true,
  hero_eyebrow: "2006 - 2026",
  hero_title: "Pre HC 2006",
  hero_tagline: "O reencontro de 20 anos",
  hero_subtitle: "",
  hero_event_line: "17 de outubro de 2026 - Natal/RN",
  primary_cta_label: "Comprar ingresso",
  primary_cta_page: "tickets",
  secondary_cta_label: "Ver quem vai",
  secondary_cta_page: "who-going",
  countdown_days_label: "Dias",
  countdown_hours_label: "Horas",
  countdown_minutes_label: "Min",
  countdown_seconds_label: "Seg",
  about_eyebrow: "Sobre",
  about_title: "Nossa historia",
  about_body_1: "Uma turma que volta a se encontrar.",
  about_body_2: "Memorias, perfis e conexoes reais.",
  info_eyebrow: "Evento",
  info_title: "Data, hora e local",
  info_date_label: "Data",
  info_time_label: "Horario",
  info_location_label: "Local",
  info_doors_subtitle_template: "Portas as {time}",
  info_dinner_subtitle_template: "Jantar as {time}",
  info_time_fallback_label: "Horario a confirmar",
  event_info_view_more_label: "Ver mais",
  tickets_eyebrow: "Ingressos",
  tickets_title: "Escolha seu ingresso",
  tickets_preview_limit: "3",
  tickets_view_all_label: "Ver todos",
  tickets_active_lot_label: "Lote atual",
  tickets_buy_label: "Comprar",
  tickets_sold_out_label: "Esgotado",
  tickets_empty_title: "Vendas em breve",
  tickets_empty_subtitle: "Aguarde a abertura das vendas.",
  tickets_empty_cta_label: "Saiba mais",
  tickets_remaining_label_template: "{available} de {total} restantes",
  confirmed_eyebrow: "Ex-alunos",
  confirmed_title: "A turma em movimento",
  confirmed_preview_limit: "30",
  confirmed_view_all_label: "Ver todos",
  confirmed_privacy_note: "Somente perfis publicos.",
  photos_eyebrow: "Fotos",
  photos_title: "Nossa historia em imagens",
  photos_preview_limit: "6",
  photos_view_all_label: "Ver fotos",
  photos_empty_title: "Fotos em breve",
  photos_empty_subtitle: "O acervo esta sendo preparado.",
  photos_empty_cta_label: "Ver mural",
  timeline_eyebrow: "Linha do tempo",
  timeline_title: "Nossa historia",
  timeline_items_json: JSON.stringify([
    { year: "2003", label: "Inicio do ensino medio", desc: "Um novo ciclo.", is_visible: true },
    { year: "2006", label: "Formatura", desc: "A despedida da escola.", is_visible: true },
  ]),
  faq_eyebrow: "FAQ",
  faq_title: "Perguntas frequentes",
  faq_items_json: JSON.stringify([{ q: "Quando sera?", a: "Em outubro de 2026.", is_visible: true }]),
  footer_links_json: JSON.stringify([{ page: "event", label: "Evento", is_visible: true }]),
  footer_eyebrow: "Turma 2006",
  footer_title: "Vinte anos depois",
  footer_body: "O reencontro da nossa turma.",
  footer_nav_title: "Navegacao",
  footer_contact_title: "Contato",
  footer_email: "contato@example.com",
  footer_phone: "",
  footer_location: "Natal/RN",
  footer_copyright: "Turma 2006",
  footer_terms_label: "Termos",
  footer_privacy_label: "Privacidade",
  footer_admin_label: "Admin",
  home_sections_json: JSON.stringify(restoredSections),
  home_about_overview_json: JSON.stringify(restoredAboutCopy),
  home_alumni_overview_json: JSON.stringify(alumniCopy),
  home_nostalgia_timeline_json: JSON.stringify([
    { year: "1996", icon: "laptop", title: "Internet discada", description: "Um marco da turma." },
    { year: "2006", icon: "book-image", title: "Formatura", description: "O fim de um ciclo." },
  ]),
  home_profile_stats_json: JSON.stringify([
    { key: "women", label: "são mulheres", mode: "auto", fallback_value: "0%" },
    { key: "married", label: "são casadas", mode: "auto", fallback_value: "0%" },
    { key: "children", label: "têm filhos", mode: "auto", fallback_value: "0%" },
  ]),
  home_map_stats_json: JSON.stringify([
    { key: "natal", label: "Natal/RN", mode: "auto", fallback_value: 0 },
    { key: "interior", label: "Interior do RN", mode: "auto", fallback_value: 0 },
    { key: "other_state", label: "Outros estados", mode: "auto", fallback_value: 0 },
    { key: "foreign", label: "Exterior", mode: "auto", fallback_value: 0 },
  ]),
  home_poll_id: "00000000-0000-0000-0003-000000000001",
  home_poll_fallback_json: JSON.stringify({
    empty_label: "Nenhuma enquete aberta.",
    login_required_label: "Entre para votar.",
  }),
};

const memoriesFixture = [
  { id: "00000000-0000-0000-0004-000000000001", event_id: "00000000-0000-0000-0000-000000000001", user_id: null, person_id: "00000000-0000-0000-0002-000000000001", author_name: "Pessoa 1", memory_text: "A primeira memória da turma.", is_anonymous: false, status: "approved", is_featured: true, approved_by_admin_id: null, approved_at: "2026-01-02T00:00:00Z", created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "00000000-0000-0000-0004-000000000002", event_id: "00000000-0000-0000-0000-000000000001", user_id: null, person_id: null, author_name: null, memory_text: "A segunda memória da turma.", is_anonymous: true, status: "approved", is_featured: false, approved_by_admin_id: null, approved_at: "2026-01-03T00:00:00Z", created_at: "2026-01-02T00:00:00Z", updated_at: "2026-01-02T00:00:00Z" },
];

const pollFixture = {
  id: "00000000-0000-0000-0003-000000000001",
  event_id: "00000000-0000-0000-0000-000000000001",
  question: "Qual lembrança marcou a turma?",
  description: null,
  status: "open",
  allow_multiple_votes: false,
  created_by_admin_id: null,
  created_at: "2026-01-02T00:00:00Z",
  updated_at: "2026-01-02T00:00:00Z",
  poll_options: [
    { id: "00000000-0000-0000-0005-000000000001", poll_id: "00000000-0000-0000-0003-000000000001", option_text: "A formatura", sort_order: 0, created_at: "2026-01-02T00:00:00Z" },
    { id: "00000000-0000-0000-0005-000000000002", poll_id: "00000000-0000-0000-0003-000000000001", option_text: "As gincanas", sort_order: 1, created_at: "2026-01-02T00:00:00Z" },
  ],
};

const profileStatsFixture = {
  event_id: "00000000-0000-0000-0000-000000000001",
  total_people: 8,
  total_registered: 6,
  total_preconfirmed: 0,
  total_confirmed: 0,
  total_with_relationship: 6,
  total_with_children: 3,
  total_children_declared: 5,
  relationship_status_counts: [{ label: "Casado(a)", count: 3 }, { label: "Solteiro(a)", count: 3 }],
  children_status_counts: [{ label: "Com filhos", count: 3 }, { label: "Sem filhos", count: 3 }],
  children_count_distribution: [],
  profession_area_counts: [],
};

const locationsFixture = [
  { profile_id: "l1", person_id: "p1", display_name: "Natal 1", full_name: "Natal 1", avatar_url: null, current_city: "Natal", current_state: "RN", current_country: "Brasil", profession: null, show_profession: true },
  { profile_id: "l2", person_id: "p2", display_name: "Natal 2", full_name: "Natal 2", avatar_url: null, current_city: "NATAL", current_state: "rn", current_country: "Brazil", profession: null, show_profession: true },
  { profile_id: "l3", person_id: "p3", display_name: "Interior", full_name: "Interior", avatar_url: null, current_city: "Mossoró", current_state: "RN", current_country: "Brasil", profession: null, show_profession: true },
  { profile_id: "l4", person_id: "p4", display_name: "Outro estado", full_name: "Outro estado", avatar_url: null, current_city: "Recife", current_state: "PE", current_country: "Brasil", profession: null, show_profession: true },
  { profile_id: "l5", person_id: "p5", display_name: "Exterior", full_name: "Exterior", avatar_url: null, current_city: "Lisboa", current_state: null, current_country: "Portugal", profession: null, show_profession: true },
];

const eventFixture = {
  id: "00000000-0000-0000-0000-000000000001",
  title: "Reencontro da Turma 2006",
  slug: "reencontro-20-anos",
  description: "Evento de reencontro.",
  event_date: "2026-10-17",
  event_time: "19:00:00",
  location_name: "Espaco Cultural",
  location_address: "Natal/RN",
  event_status: "published",
  sales_status: "open",
  contact_email: null,
  contact_whatsapp: null,
  general_rules: null,
  companion_policy: null,
  refund_policy: null,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
};

type InstallOptions = {
  delayHomeMs?: number;
  mutateHome?: (row: Record<string, unknown>) => void;
  people?: typeof peopleFixture;
  locations?: typeof locationsFixture;
};

export async function installHomeFixtures(page: Page, options: InstallOptions = {}) {
  await page.route("**/rest/v1/**", async route => {
    const pathname = new URL(route.request().url()).pathname;
    const resource = pathname.split("/rest/v1/")[1]?.split("/")[0] ?? "";
    if (resource === "home_page_content" && options.delayHomeMs) {
      await new Promise(resolve => setTimeout(resolve, options.delayHomeMs));
    }

    const home = structuredClone(homeContentFixture);
    options.mutateHome?.(home);
    const payloads: Record<string, unknown> = {
      home_page_content: [home],
      events: [eventFixture],
      people: options.people ?? peopleFixture,
      profiles: [],
      ticket_types: [],
      photos: [],
      memories: memoriesFixture,
      polls: [pollFixture],
      poll_results: [
        { poll_id: pollFixture.id, option_id: pollFixture.poll_options[0].id, option_text: pollFixture.poll_options[0].option_text, sort_order: 0, votes_count: 3 },
        { poll_id: pollFixture.id, option_id: pollFixture.poll_options[1].id, option_text: pollFixture.poll_options[1].option_text, sort_order: 1, votes_count: 1 },
      ],
      poll_votes: [],
      public_curiosity_profile_stats: [profileStatsFixture],
      public_profile_locations: options.locations ?? locationsFixture,
      event_page_content: [{
        event_id: eventFixture.id,
        hero_eyebrow: "Evento",
        title: eventFixture.title,
        subtitle: "Vinte anos depois",
        description: eventFixture.description,
        gallery_json: [],
        attractions_json: [],
        schedule_json: [],
        extra_info_json: [],
        venue_notes: "Informacoes do local.",
        food_bar_text: "Informacoes em breve.",
        bathrooms_text: "Informacoes em breve.",
        security_text: "Informacoes em breve.",
      }],
      event_archive_settings: [{
        event_id: eventFixture.id,
        archive_enabled: true,
        post_event_text: "Mensagem final da organizacao.",
        official_video_url: null,
        official_video_title: null,
        official_photo_ids: [],
        highlight_photo_ids: [],
        highlights_links: [],
        created_at: "2026-01-01T00:00:00Z",
        updated_at: "2026-01-01T00:00:00Z",
      }],
      rpc: [],
    };
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      headers: { "Content-Range": "0-0/1" },
      body: JSON.stringify(payloads[resource] ?? []),
    });
  });
}
